version: "2.3"

services:
  vscode:
    build:
      context: .
      dockerfile: docker/vscode.Dockerfile
    image: andyneff/vscode:latest
    environment:
      # Variables for just_entrypoint_functions
      - DOCKER_UID=${VSCODE_UID}
      - DOCKER_GIDS=${VSCODE_GIDS}
      - DOCKER_GROUP_NAMES=${VSCODE_GROUP_NAMES}
      - DOCKER_USERNAME=${VSCODE_USERNAME}
      - JUSTFILE=/vscode/docker/vscode.Justfile
      - JUST_SETTINGS=/vscode/vscode.env
      - TZ
      - VSCODE_COMMIT=${VSCODE_SERVER_SHA}
    volumes:
      - source: ${VSCODE_CWD}
        target: /vscode
        type: bind
      - source: ${VSCODE_DATA_DIR}
        target: ${VSCODE_DATA_DIR_DOCKER}
        type: ${VSCODE_DATA_DIR_TYPE}
      - source: ${VSCODE_HOME_DIR}
        target: ${VSCODE_HOME_DIR_DOCKER}
        type: ${VSCODE_HOME_DIR_TYPE}
      - source: ${VSI_COMMON_DIR}
        target: /vsi
        type: bind
    cap_add:
      - SYS_PTRACE # Useful for gdb
volumes:
  ssh_keys:
  passwd:
