#!/usr/bin/env bash

set -eu

source /vsi/linux/elements.bsh
MIFS=// split_s just_docker_entrypoint_internal_volumes "${JUST_DOCKER_ENTRYPOINT_INTERNAL_VOLUMES-}"
remove_element_a just_docker_entrypoint_internal_volumes /etc/ssh
join_a JUST_DOCKER_ENTRYPOINT_INTERNAL_VOLUMES ${just_docker_entrypoint_internal_volumes[@]+"${just_docker_entrypoint_internal_volumes[@]}"} || : #don't care if it's empty
export JUST_DOCKER_ENTRYPOINT_INTERNAL_VOLUMES
